### ISSUE TITLE
Anti-Cheat Bans Notification BUG

### ISSUE THREAD

**Issue by shaikhnedab** [TheByKotik/sbpp_discord#14] opened 2022-01-13 09:17 UTC
Found a weird bug.
Normal bans (i.e. manually banning using sm_ban) sends notification to discord channel normally.
But if any  Anti-Cheat (tried on Little AC and SMAC) auto bans user it doesn't sends notification to discord channel.

It used to work on older version ``(1.7.0-49)``
here is the embed screenshot for older version.
![image](https://user-images.githubusercontent.com/55206494/149300505-361a2a82-6029-490c-be58-3046825852a0.png).

Current Plugin Version : ``1.7.0-51``

I have not changed anything with SMAC or Sourceban plugin. It is happening after updating to ``(1.7.0-51)``

**Comment by TheByKotik** [comment] 2022-01-13 11:04
Hi!
1. Do you use precompiled .smx (sbpp_discord & lilac / smac) or compiled by yourself?
2. Which version of SB++ used?

**Comment by shaikhnedab** [comment] 2022-01-13 18:44
Hello,

1. Yes precompiled .smx from respective repositories.
 a. [Little Anti-Cheat](https://github.com/J-Tanzanite/Little-Anti-Cheat)
 b. Sourceban++ 1.6.4

It was working fine on older version as mentioned.

**Comment by TheByKotik** [comment] 2022-01-14 11:11
*Weird*

I can't reproduce that bug. In any cases i always receive notification embed.
![image](https://user-images.githubusercontent.com/40791562/149505368-059ae2e1-e710-4b3c-aa8a-46d8ac255d88.png)

I created [fork of lilac](https://github.com/TheByKotik/Little-Anti-Cheat) with debuggers, please give it a try and report console outputs here.
Command `sm_test` must directly call `lilac_ban_client` .

**Comment by TheByKotik** [comment] 2022-01-14 11:32
Also are you sure sbpp_discord isn't throwing exception like this: `Exception reported: Language phrase "Blocked by" not found (arg 5)`?
This exception was fixed in 3230613 (1.7.0-52).

**Comment by shaikhnedab** [comment] 2022-01-14 17:39
well that was it ``Exception reported: Language phrase "Blocked by" not found (arg 5)``.
for some reason there were no error logs with above error. but when I tested with lilac debug mode I saw those errors in server console. updating to 1.7.0-52 fixed the issue.
Thank you very much

**Closed as completed** 2022-07-27 14:12 UTC
